language: python
cache: pip
python:
  - "3.6"
  - "3.5"
install:
  - pip install -r requirements_dev.txt
script:
  - flake8
  - python -m pytest tests/
  - "if [ \"$TRAVIS_BRANCH\" != \"master\" ] || [\"$TRAVIS_PULL_REQUEST\" != \"false\"]; then ./.travis.version.upgrades.needed.sh; fi"
